ALTER TABLE 活动
ADD CONSTRAINT 举办社团编号约束
	FOREIGN KEY(举办社团编号) REFERENCES 社团(社团编号)
		ON UPDATE CASCADE; 

ALTER TABLE 社团人员名单
ADD CONSTRAINT 社团人员约束 
	FOREIGN KEY (学号) REFERENCES 学生(学号)
		ON UPDATE CASCADE; 
ALTER TABLE 社团人员名单
ADD CONSTRAINT 社团编号约束 
	FOREIGN KEY (社团编号) REFERENCES 社团(社团编号)
		ON UPDATE CASCADE; ;

		
ALTER TABLE 活动人员名单
ADD CONSTRAINT 活动成员约束 
	FOREIGN KEY (学号) REFERENCES 学生(学号)
		ON UPDATE CASCADE;
ALTER TABLE 活动人员名单
ADD CONSTRAINT 活动编号约束 
	FOREIGN KEY (活动编号) REFERENCES 活动(活动编号)
		ON UPDATE CASCADE; 
